# Generated by Django 5.1.5 on 2025-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
    ]
