# Generated by Django 5.1.5 on 2025-01-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='telefone',
            new_name='Telefone',
        ),
    ]
