# Generated by Django 5.1.5 on 2025-01-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_telefone_pessoa_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='Telefone',
            new_name='telefone',
        ),
    ]
